version: '3'
services:
    pg:
      image: postgres:13
      container_name: pg
      volumes:
        - pgdbdata:/var/lib/postgresql/data/
      env_file:
        - ./postgres_to_es/.env
      expose:
        - "5432"
      restart: always

    elastic:
      image: ghcr.io/yp-middle-python-24/elasticsearch:8.7.0
      container_name: elastic
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - network.bind_host=0.0.0.0
        - ES_JAVA_OPTS=-Xms200m -Xmx200m
      ports:
        - "9200:9200"
      restart: on-failure

    etl:
        container_name: etl
        build:
          context: ./postgres_to_es
        env_file:
          - ./postgres_to_es/.env
        depends_on:
          - elastic
          - pg
        restart: unless-stopped




volumes:
  pgdbdata:
